### ISSUE TITLE
X-axis ranges misaligned in ES histogram window

### ISSUE THREAD

**Issue by simonbonano** [hatzakislab/DeepFRET-GUI#16]
The x-axis ranges of the E and S histograms do not align with the ES scatter/contour plot in the histogram window. This is not urgent, but should be fixed.

[2D_histogram_all_frames_n2009.pdf](https://github.com/hatzakislab/DeepFRET-GUI/files/5194265/2D_histogram_all_frames_n2009.pdf)

**Comment by komodovaran** [comment]
https://github.com/hatzakislab/DeepFRET-GUI/pull/17 should fix.
