### ISSUE TITLE
Predict tool with real data gives confidence  <35% 

### ISSUE THREAD

**Issue by shiekh-phy** [hatzakislab/DeepFRET-GUI#8]
With predict trace tool, I always get a confidence level of <35%. Does this mean the data is too noisy or some issues with the program.

**Comment by eembees** [comment]
The predict trace tool depends largely on what model you're using (they're placed in `src/main/resources/base` ), which are tailored to the thermodynamics of the system we've simulated (more info on that is in our [relevant publication](https://www.biorxiv.org/content/10.1101/2020.06.26.173260v1) ). 
If you want to train your own models on your own simulated data, you can use the code found [at this repository](https://github.com/hatzakislab/DeepFRET-Model) to simulate data and train models that better represent your system.  
Hope this helps!
